#include <iostream>
using namespace std;

// TWO APPROACH AS TOLD BY LOVE BABBAR
// 1. RECURSIVE APPROACH WITH FURTHUR DP OPTIMIZATION
// 2. BINARY SEARCH APPROACH BUT THERE IS SOME CONDITION TO SET WHILE SORTING 
// CHECK THE IMAGE TO BETTER UNDERSTAND CONDITION
int main()
{
    return 0;
}